### ISSUE TITLE
【意见】请认真对待开放出来的SDK

### ISSUE THREAD

**Issue by orxz** [baidu/smartapp-openapi-php#1]
骂人的话省略了。。。
请问这个sdk是不是百度官方的SDK？是否可用线上使用？是否有代码审核？是否有测试？

-------------------

随便举例疑问：

例如0.1.2版本中，查看https://github.com/baidu/smartapp-openapi-php/blob/0.1.2/src/HttpClient.php

` 
...

class HttpClient{
    private $ch;
    private $contentType;
    private $method;
    private $getParam;
    private $postParam;
    private $host;
    private $path;
    private $headers;
...

 //formatURL 设置url
    private function formatURL(){
        $url = "https://" . $this->host . $this->path . "?" . http_build_query($this->getParam);
        return $url;
    }`

...

不说调用细节了，就拿这个formatURL方法来说，**post请求的时候getParam是null，那在0.1.2版本中post请求都是会报错的。之前我是手动兼容的**
处理方法也很简单，private $getParam=[];就行了

在看0.1.3版本https://github.com/baidu/smartapp-openapi-php/blob/0.1.3/src/HttpClient.php
确实是给了默认值
`
class HttpClient{
    private $ch;
    private $contentType;
    private $method;
    private $getParam = array();
    private $postParam = array();
    private $host;
    private $path;
    private $headers;
`

好的，那看来之前是有bug的对吧。。不说这次更新改的其他东西。

再举例一个0.1.3的更新
<img width="663" alt="image" src="https://user-images.githubusercontent.com/64585115/160869016-25755e62-f82a-4764-bdf7-c3f0bc7c964e.png">

**新增了一个参数而且没有默认值？那sdk中调用的还是老的代码没有更新全部报错。**
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/64585115/160872520-07b54eeb-2953-4590-8ca8-79f4a0d74842.png">

内部的方法你们怎么改都随意，可是你们没封装直接扔出来给大家用，然后又每次搞这些低级错误。

所以请问SDK是否有代码审核？是否有测试？
@msfruit

**Comment by msfruit** [comment]
您好，非常抱歉，原因是我们上次打包时误选错了分支，另一个问题是由于疏忽没有进行发布后的测试。
目前我们已经更正了错误并重新发了新版 0.1.4。
非常感谢您的反馈。
